[package]
name = "nimiq-client"
version = "0.1.0"
authors = ["Janosch Gräf <janosch.graef@cispa.saarland>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq's Rust client"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
serde = "1.0.85"
serde_derive = "1.0.85"
toml = "0.4.10"
log = "0.4.6"
pretty_env_logger = "0.2.3"
dotenv = "0.13.0"
futures = "0.1"
nimiq-database = { path = "../database" }
nimiq-network = { path = "../network" }
nimiq-consensus = { path = "../consensus" }
nimiq-primitives = { path = "../primitives" }
tokio = "0.1"
lazy_static = "1.0"