[package]
name = "nimiq-client"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq's Rust client"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
serde = "1.0.85"
serde_derive = "1.0.85"
toml = "0.4.10"
log = "0.4.6"
fern = { version = "0.5", features = ["colored"] }
futures = "0.1"
tokio = "0.1"
lazy_static = "1.0"
parking_lot = { version = "0.6", optional = true, features = ["deadlock_detection"] }
hyper = { version = "0.12.19", optional = true }
clap = "2.32"
nimiq-database = { path = "../database" }
nimiq-network = { path = "../network" }
nimiq-consensus = { path = "../consensus" }
nimiq-primitives = { path = "../primitives" }
nimiq-rpc-server = { path = "../rpc-server", optional = true }
nimiq-metrics-server = { path = "../metrics-server", optional = true }
nimiq-lib = { path = "../lib" }
colored = "1.7.0"
chrono = "0.4.6"
failure = "0.1.5"
failure_derive = "0.1.5"

[features]
default = ["all"]
all = ["rpc-server", "metrics-server", "deadlock-detection"]
rpc-server = ["nimiq-rpc-server", "hyper"]
metrics-server = ["nimiq-metrics-server", "hyper"]
deadlock-detection = ["parking_lot"]
