#
# Configuration for Nimiq core-rs node
#
#   WARNING !!
#   This is a test configuration for development. DO NOT USE.
#

[network]
host = "my.domain"
protocol = "ws"
user_agent = "core-rs/dev (native; Linux x64)"

[consensus]
type = "full"
network = "test"

[log]
level = "trace"
timestamps = true

[rpcServer]
port = 8648

[metricsServer]