[package]
name = "nimiq-collections"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>"]
edition = "2018"
description = "A set of advanced collections for use in the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }

[dev-dependencies]
rand = "0.4"
