[package]
name = "nimiq-collections"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>"]
edition = "2018"
description = "A set of advanced collections for use in the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
itertools = { version = "0.8", optional = true }
beserial = { path = "../beserial", optional = true }
beserial_derive = { path = "../beserial/beserial_derive", optional = true }
num-traits = "0.2"

[dev-dependencies]
rand = "0.6"
hex = "0.3"

[features]
bitset = ["itertools", "beserial", "beserial_derive"]
