[package]
name = "nimiq-accounts"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Persistent accounts storage for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../beserial" }
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives", features = ["coin", "networks", "policy"] }
nimiq-hash = { path = "../hash" }
nimiq-account = { path = "../primitives/account" }
nimiq-block = { path = "../primitives/block" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-database = { path = "../database", features = ["full-nimiq"] }
hex = "0.3.2"
parking_lot = "0.6"
nimiq-tree-primitives = { path = "./tree-primitives" }
nimiq-utils = { path = "../utils", features = ["observer", "unique-ptr"] }
nimiq-network-primitives = { path = "../network-primitives", features = ["networks"] }

[dev-dependencies]
atomic = "0.4"
pretty_env_logger = "0.2.3"
