[package]
name = "nimiq-account"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Account primitives to be used in Nimiq's Albatross implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
hex = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
parking_lot = "0.12"
rand = "0.8"
serde = "1.0"
strum_macros = "0.24"
thiserror = "1.0"

nimiq-bls = { path = "../../bls" }
nimiq-collections = { path = "../../collections" }
nimiq-database = { path = "../../database", optional = true }
nimiq-database-value = { path = "../../database/database-value" }
nimiq-hash = { path = "../../hash" }
nimiq-keys = { path = "../../keys", features = ["serde-derive"] }
nimiq-macros = { path = "../../macros" }
nimiq-primitives = { path = "..", features = ["coin", "policy", "serde-derive", "slots", "tree-proof", "trie"] }
nimiq-serde = { path = "../../serde" }
nimiq-transaction = { path = "../transaction" }
nimiq-trie = { path = "../trie", optional = true }
nimiq-utils = { path = "../../utils", features = ["key-rng"] }
nimiq-vrf = { path = "../../vrf" }

[dev-dependencies]
hex = "0.4"
tempfile = "3.3"

nimiq-genesis-builder = { path = "../../genesis-builder" }
nimiq-test-log = { path = "../../test-log" }
nimiq-test-utils = { path = "../../test-utils" }

[features]
accounts = ["interaction-traits", "nimiq-database", "nimiq-trie"]
default = ["accounts", "interaction-traits"]
interaction-traits = ["nimiq-database"]
