[package]
name = "nimiq-account"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Account primitives to be used in Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
log = "0.4"
failure = "0.1"
parking_lot = "0.7"
lazy_static = "1.3"
beserial = { path = "../../beserial", version = "0.1.0" }
beserial_derive = { path = "../../beserial/beserial_derive", version = "0.1.0" }
nimiq-hash = { path = "../../hash", version = "0.1.0" }
nimiq-keys = { path = "../../keys", version = "0.1.0" }
nimiq-transaction = { path = "../transaction", version = "0.1.0" }
nimiq-primitives = { path = "..", version = "0.1.0", features = ["coin", "policy"] }
nimiq-bls = { path = "../../bls", version = "0.1.0" }
nimiq-collections = { path = "../../collections" }

[dev-dependencies]
hex = "0.3"
rand = "0.6"
