[package]
name = "nimiq-account"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Account primitives to be used in Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }

[dependencies]
beserial = { path = "../../beserial" }
beserial_derive = { path = "../../beserial/beserial_derive"}
nimiq-hash = { path = "../../hash" }
nimiq-keys = { path = "../../keys" }
nimiq-transaction = { path = "../transaction" }
nimiq-primitives = { path = "..", features = ["coin"] }
log = "0.4"

[dev-dependencies]
nimiq-transaction = { path = "../transaction" }
hex = "0.3.2"
