[package]
name = "nimiq-blockchain-albatross"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Persistent block storage for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
nimiq-bls = { path = "../bls", features = ["beserial"]}
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives" }
nimiq-account = { path = "../primitives/account" }
nimiq-block-albatross = { path = "../primitives/block-albatross" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-hash = { path = "../hash" }
nimiq-accounts = { path = "../accounts" }
nimiq-database = { path = "../database", features = ["full-nimiq"] }
nimiq-tree-primitives = { path = "../accounts/tree-primitives" }
fixed-unsigned = { path = "../fixed-unsigned" }
nimiq-utils = { path = "../utils", features = ["observer", "unique-ptr", "iterators"] }
nimiq-network-primitives = { path = "../network-primitives", features = ["networks", "time"] }
nimiq-blockchain-base = { path = "../blockchain-base" }
parking_lot = "0.7"
log = "0.4"
hex = "0.3"
failure = "0.1"

[dev-dependencies]
atomic = "0.4"

[features]
default = ["transaction-store"]
metrics = []
transaction-store = []
