[package]
name = "nimiq-blockchain-albatross"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Persistent block storage for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
failure = "0.1"
hex = "0.3"
log = "0.4"
parking_lot = "0.7"
beserial = { path = "../beserial", version = "0.1.0" }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.1.0" }
fixed-unsigned = { path = "../fixed-unsigned", version = "0.1.0" }
nimiq-account = { path = "../primitives/account", version = "0.1.0" }
nimiq-accounts = { path = "../accounts", version = "0.1.0" }
nimiq-block-albatross = { path = "../primitives/block-albatross", version = "0.1.0" }
nimiq-blockchain-base = { path = "../blockchain-base", version = "0.1.0" }
nimiq-bls = { path = "../bls", version = "0.1.0", features = ["beserial"] }
nimiq-database = { path = "../database", version = "0.1.0", features = ["full-nimiq"] }
nimiq-keys = { path = "../keys", version = "0.1.0" }
nimiq-hash = { path = "../hash", version = "0.1.0" }
nimiq-network-primitives = { path = "../network-primitives", version = "0.1.0", features = ["networks", "time"] }
nimiq-primitives = { path = "../primitives", version = "0.1.0" }
nimiq-transaction = { path = "../primitives/transaction", version = "0.1.0" }
nimiq-tree-primitives = { path = "../accounts/tree-primitives", version = "0.1.0" }
nimiq-utils = { path = "../utils", version = "0.1.0", features = ["observer", "unique-ptr", "iterators"] }

[dev-dependencies]
atomic = "0.4"

[features]
default = ["transaction-store"]
metrics = ["nimiq-blockchain-base/metrics"]
transaction-store = []
