[package]
name = "nimiq-blockchain-albatross"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Persistent block storage for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
failure = "0.1"
hex = "0.3"
log = "0.4"
parking_lot = "0.9"
beserial = { version = "0.1" }
beserial_derive = { version = "0.1" }
fixed-unsigned = { version = "0.1" }
nimiq-account = { version = "0.1" }
nimiq-accounts = { version = "0.1" }
nimiq-block-albatross = { version = "0.1" }
nimiq-blockchain-base = { version = "0.1" }
nimiq-collections = { version = "0.1" }
nimiq-bls = { version = "0.1", features = ["beserial"] }
nimiq-database = { version = "0.1", features = ["full-nimiq"] }
nimiq-keys = { version = "0.1" }
nimiq-hash = { version = "0.1" }
nimiq-network-primitives = { version = "0.1", features = ["networks", "time"] }
nimiq-primitives = { version = "0.1" }
nimiq-transaction = { version = "0.1" }
nimiq-tree-primitives = { version = "0.1" }
nimiq-utils = { version = "0.1", features = ["observer", "unique-ptr", "iterators"] }

[dev-dependencies]
atomic = "0.4"
rand = "0.6"
nimiq-block-production-albatross = { version = "0.1" }

[features]
default = ["transaction-store"]
metrics = ["nimiq-blockchain-base/metrics"]
transaction-store = []
