[package]
name = "nimiq-blockchain-albatross"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Persistent block storage for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
failure = "0.1"
hex = "0.4"
log = "0.4"
parking_lot = "0.9"
rand = "0.7"
beserial = "0.1"
beserial_derive = "0.1"
fixed-unsigned = "0.1"
nimiq-account = "0.1"
nimiq-accounts = "0.1"
nimiq-block-albatross = "0.1"
nimiq-blockchain-base = "0.1"
nimiq-collections = "0.1"
nimiq-bls = { version = "0.1", features = ["beserial"] }
nimiq-database = { version = "0.1", features = ["full-nimiq"] }
nimiq-keys = "0.1"
nimiq-hash = "0.1"
nimiq-network-primitives = { version = "0.1", features = ["networks", "time"] }
nimiq-primitives = "0.1"
nimiq-transaction = "0.1"
nimiq-tree-primitives = "0.1"
nimiq-utils = { version = "0.1", features = ["observer", "unique-ptr", "iterators"] }

[dev-dependencies]
atomic = "0.4"
nimiq-block-production-albatross = "0.1"

[features]
default = ["transaction-store"]
metrics = ["nimiq-blockchain-base/metrics"]
transaction-store = []
