[package]
name = "nimiq-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Primitives (e.g., block, account, transaction) to be used in Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
bigdecimal = { version = "0.0.14", optional = true }
num-bigint = { version = "0.2.0", optional = true }
num-traits = { version = "0.2.6", optional = true }
parking_lot = { version = "0.6", optional = true }
hex = { version = "0.3.2", optional = true }
lazy_static = { version = "1.0", optional = true }
bitflags = { version = "1.0", optional = true }
log = { version = "0.4.3", optional = true }
nimiq-hash = { path = "../hash", optional = true }
nimiq-keys = { path = "../keys", optional = true }
nimiq-macros = { path = "../macros", optional = true }
nimiq-utils = { path = "../utils", optional = true, features = ["merkle"] }

[features]
all = ["coin", "account", "block", "policy", "transaction", "networks", "proof"]
coin = ["hex"]
account = ["nimiq-keys", "coin", "nimiq-hash", "hex", "nimiq-macros", "log"]
block = ["bigdecimal", "num-bigint", "nimiq-hash", "policy", "nimiq-utils", "account", "nimiq-keys", "transaction", "networks"]
policy = ["bigdecimal", "num-bigint", "num-traits", "parking_lot", "lazy_static"]
transaction = ["nimiq-hash", "nimiq-utils", "policy", "networks", "bitflags", "log", "nimiq-keys", "account"]
networks = []
proof = ["block"]
