[package]
name = "nimiq-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Primitives (e.g., block, account, transaction) to be used in Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
num-bigint = { version = "0.2.0", optional = true }
num-traits = { version = "0.2.6", optional = true }
fixed-unsigned = { path = "../fixed-unsigned", optional = true }
parking_lot = { version = "0.6", optional = true }
hex = { version = "0.3.2", optional = true }
lazy_static = { version = "1.0", optional = true }
nimiq-macros = { path = "../macros", optional = true }
log = { version = "0.4.3", optional = true }

[dev-dependencies]
lazy_static = "1.2"

[features]
all = ["coin", "account", "policy", "networks"]
coin = ["hex", "log"]
account = ["hex", "nimiq-macros"]
policy = ["num-bigint", "num-traits", "parking_lot", "lazy_static", "fixed-unsigned"]
networks = []
