[package]
name = "primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
bigdecimal = { version = "0.0.14", optional = true }
num-bigint = { version = "0.2.0", optional = true }
num-traits = { version = "0.2.6", optional = true }
parking_lot = { version = "0.6", optional = true }
hex = { version = "0.3.2", optional = true }
lazy_static = { version = "1.0", optional = true }
bitflags = { version = "1.0", optional = true }
log = { version = "0.4.3", optional = true }
hash = { path = "../hash", optional = true }
keys = { path = "../keys", optional = true }
macros = { path = "../macros", optional = true }
utils = { path = "../utils", optional = true, features = ["merkle"] }

[features]
all = ["coin", "account", "block", "policy", "transaction", "networks"]
coin = []
account = ["keys", "coin", "hash", "hex", "macros", "log"]
block = ["bigdecimal", "num-bigint", "hash", "policy", "utils", "account", "keys", "transaction", "networks"]
policy = ["bigdecimal", "num-bigint", "num-traits", "parking_lot", "lazy_static"]
transaction = ["hash", "utils", "policy", "networks", "bitflags", "log", "keys", "account"]
networks = []
