[package]
authors = ["Jack Grigg <str4d@i2pmail.org>", "The Nimiq Core Development Team <info@nimiq.com>"]
description = "BLS signatures"
documentation = "https://github.com/nimiq/bls"
homepage = "https://github.com/nimiq/bls"
license = "MIT/Apache-2.0"
name = "nimiq-bls"
repository = "https://github.com/nimiq/bls"
version = "0.1.0"
edition = "2018"

[dependencies]
pairing = { git = "https://github.com/paberr/librustzcash" }
group = { git = "https://github.com/paberr/librustzcash" }
ff = { git = "https://github.com/paberr/librustzcash" }
nimiq-hash = { path = "../hash" }
rand = "0.6"
rand04_compat = "0.1"
rand_chacha = "0.1"
hashmap_core = "0.1"
beserial = { path = "../beserial", version = "0.1.0", optional = true }
hex = "0.3"
parking_lot = { version = "0.7", optional = true }

[dev-dependencies]
rand_xorshift = "0.1"

[features]
default = ["std", "beserial", "lazy"]
std = []
lazy = ["parking_lot"]
