[package]
authors = ["Jack Grigg <str4d@i2pmail.org>", "The Nimiq Core Development Team <info@nimiq.com>"]
description = "BLS signatures"
documentation = "https://github.com/nimiq/bls"
homepage = "https://github.com/nimiq/bls"
license = "MIT/Apache-2.0"
name = "nimiq-bls"
repository = "https://github.com/nimiq/bls"
version = "0.0.1"
edition = "2018"

[dependencies]
pairing = "0.14"
rand = "0.6"
rand04_compat = "0.1"
rand_chacha = "0.1"
tiny-keccak = "1.4"
hashmap_core = "0.1"
byteorder = "1.3"

[dev-dependencies]
rand_xorshift = "0.1"

[features]
default = ["std"]
std = []