[package]
authors = ["Jack Grigg <str4d@i2pmail.org>", "The Nimiq Core Development Team <info@nimiq.com>"]
description = "BLS signatures"
documentation = "https://github.com/nimiq/bls"
homepage = "https://github.com/nimiq/bls"
license = "MIT/Apache-2.0"
name = "nimiq-bls"
repository = "https://github.com/nimiq/bls"
version = "0.1.0"
edition = "2018"

[dependencies]
pairing = { git = "https://github.com/paberr/librustzcash" }
group = { git = "https://github.com/paberr/librustzcash" }
ff = { git = "https://github.com/paberr/librustzcash" }
nimiq-hash = "0.1"
rand = "0.7"
rand_chacha = "0.2"
hashbrown = "0.6"
beserial = { version = "0.1", optional = true }
hex = "0.4"
parking_lot = { version = "0.9", optional = true }
failure = "0.1"

[dev-dependencies]
rand_xorshift = "0.2"

[features]
default = ["std", "beserial", "lazy"]
std = []
lazy = ["parking_lot"]
