image: 'rust:latest'
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

stages:
  - build
  - test
  - coverage
  - deploy

.build:
  stage: build
  script:
    - rustc --version
    - cargo --version
    - cargo build --all
  artifacts:
    paths:
      - target/debug/nimiq-client

.test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --all

.coverage:
  stage: coverage
  script:
    - rustc --version
    - cargo --version
    - apt-get update -yq
    - apt-get install -y cmake libelf-dev libdw-dev binutils-dev libiberty-dev jq
    - ./scripts/coverage.sh --all --tests
  artifacts:
    paths:
      - cov/cov

#build-nightly:
#  extends: .build
#  image: 'rustlang/rust:nightly'

test-nightly:
  extends: .test
  image: 'rustlang/rust:nightly'
#  dependencies:
#    - build-nightly

coverage-nightly:
  extends: .coverage
  image: 'rustlang/rust:nightly'

#build-stable:
#  extends: .build

#test-stable:
#  extends: .test
#  dependencies:
#    - build-stable

#coverage-stable:
#  extends: .coverage
#  dependencies:
#    - build-stable

.pages:
  stage: deploy
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=nimiq">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

# stable
#pages:
#  extends: .pages

# nightly
#pages:
#  extends: .pages
#  image: 'rustlang/rust:nightly'
