[package]
name = "nimiq"
version = "0.0.1"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
description = "Nimiq Core implementation in Rust"
repository = "https://github.com/nimiq-network/core-rs"
homepage = "https://nimiq.com"

# Remove sometime
publish = false

[lib]

[dependencies]
beserial = { path = "beserial" }
beserial_derive = { path = "beserial/beserial_derive"}
bit-vec = "0.5.0"
bitflags = "1.0"
blake2-rfc = "0.2.18"
curve25519-dalek = "0.18"
ed25519-dalek = "0.6.2"
hex = "0.3.2"
lazy_static = "1.0"
libargon2-sys = { path = "libargon2-sys" }
log = "0.4.3"
rand = "0.4.2"
sha2 = "0.7.1"
lmdb-zero = "0.4.4"
fs2 = "0.4.3"
parking_lot = "0.6"
unicode-normalization = "0.1.7"
tempdir = "0.3"

url = "1.7"
tokio = "0.1"
futures = "0.1"
byteorder = "1.2"
tungstenite = "0.6"
tokio-tungstenite = "0.6"
regex = "1"

[dev-dependencies]
pretty_env_logger = "0.2.3"


[workspace]
members = [
    "libargon2-sys",
    "beserial",
]
