[package]
name = "core-rs"
version = "0.0.1"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]

[dependencies]
hex = "0.3.2"
blake2-rfc = "0.2.18"
sha2 = "0.7.1"
libargon2-sys = { path = "libargon2-sys" }

[workspace]
members = [
    "libargon2-sys",
]
