[workspace]
members = [
    "libargon2-sys",
    "beserial",
    "collections",
    "database",
    "hash",
    "macros",
    "keys",
    "key-derivation",
    "mnemonic",
    "utils",
    "primitives",
    "blockchain",
    "accounts",
    "mempool",
    "network-primitives",
    "consensus",
    "network",
    "client",
    "rpc-server",
    "metrics-server",
    "lib",
    "messages",
]
