[workspace]
members = [
    "libargon2-sys",
    "beserial",
    "beserial/beserial_derive",
    "collections",
    "database",
    "hash",
    "hash/hash_derive",
    "macros",
    "keys",
    "key-derivation",
    "mnemonic",
    "utils",
    "primitives",
    "primitives/account",
    "primitives/block",
    "primitives/block-albatross",
    "primitives/transaction",
    "blockchain",
    "blockchain-albatross",
    "accounts",
    "accounts/tree-primitives",
    "mempool",
    "network-primitives",
    "consensus",
    "network",
    "client",
    "rpc-server",
    "metrics-server",
    "lib",
    "messages",
    "fixed-unsigned",
    "bls",
    "validator",
    "tools",
    "build-tools"
]
