[package]
name = "nimiq"
version = "0.0.1"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
description = "Nimiq Core implementation in Rust"
repository = "https://github.com/nimiq-network/core-rs"
homepage = "https://nimiq.com"
edition = "2018"

# Remove sometime
publish = false

[lib]

[dependencies]
network = { path = "network" }
network-primitives = { path = "network-primitives" }
primitives = { path = "primitives" }
consensus = { path = "consensus" }
database = { path = "database" }
log = "0.4.3"
pretty_env_logger = "0.2.3"
parking_lot = "0.6"
lazy_static = "1.0"
url = "1.7"
tokio = "0.1"
tokio-tls = "0.2"
native-tls = "0.2"
futures = "0.1"
tungstenite = "0.6"
tokio-tungstenite = { git = "https://github.com/jeffesquivels/tokio-tungstenite", branch = "implement_peer_addr" }

[workspace]
members = [
    "libargon2-sys",
    "beserial",
    "extended-collections",
    "database",
    "hash",
    "macros",
    "keys",
    "key-derivation",
    "mnemonic",
    "utils",
    "primitives",
    "datastructures",
    "network-primitives",
    "consensus",
    "network",
    "nimiq_bin",
]
