[package]
name = "core-rs"
version = "0.0.1"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]

[[bin]]
name = "lib"
path = "src/lib.rs"

[dependencies]
beserial = { path = "beserial" }
beserial_derive = { path = "beserial/beserial_derive"}
bit-vec = "0.5.0"
blake2-rfc = "0.2.18"
curve25519-dalek = "0.18"
ed25519-dalek = "0.6.2"
hex = "0.3.2"
libargon2-sys = { path = "libargon2-sys" }
rand = "0.4.2"
sha2 = "0.7.1"

[workspace]
members = [
    "libargon2-sys",
    "beserial",
]
