[package]
name = "nimiq"
version = "0.0.1"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
description = "Nimiq Core implementation in Rust"
repository = "https://github.com/nimiq-network/core-rs"
homepage = "https://nimiq.com"
edition = "2018"

# Remove sometime
publish = false

[lib]

[dependencies]
atomic = "0.4"
beserial = { path = "beserial" }
beserial_derive = { path = "beserial/beserial_derive"}
bit-vec = "0.5.0"
bitflags = "1.0"
hex = "0.3.2"
lazy_static = "1.0"
database = { path = "database", features = ["full-nimiq"] }
utils = { path = "utils", features = ["full-nimiq"] }
log = "0.4.3"
rand = "0.6.4"
parking_lot = "0.6"
unicode-normalization = "0.1.7"
bigdecimal = "0.0.14"
num-traits = "0.2.6"
num-bigint = "0.2.0"
weak-table = "0.2.3"
hash = { path = "hash" }
keys = { path = "keys" }
macros = { path = "macros" }
primitives = { path = "primitives", features = ["all"] }

url = "1.7"
tokio = "0.1"
tokio-tls = "0.2"
native-tls = "0.2"
futures = "0.1"
byteorder = "1.2"
tungstenite = "0.6"
tokio-tungstenite = { git = "https://github.com/jeffesquivels/tokio-tungstenite", branch = "implement_peer_addr" }
regex = "1"
pretty_env_logger = "0.2.3"


[workspace]
members = [
    "libargon2-sys",
    "beserial",
    "extended-collections",
    "database",
    "hash",
    "macros",
    "keys",
    "key-derivation",
    "mnemonic",
    "utils",
    "primitives",
    "nimiq_bin",
]
