cargo-features = ["profile-overrides"]

[workspace]
members = [
    "libargon2-sys",
    "beserial",
    "beserial/beserial_derive",
    "collections",
    "database",
    "hash",
    "hash/hash_derive",
    "macros",
    "keys",
    "key-derivation",
    "mnemonic",
    "utils",
    "primitives",
    "primitives/account",
    "primitives/block",
    "primitives/block-albatross",
    "primitives/block-base",
    "primitives/transaction",
    "blockchain",
    "blockchain-albatross",
    "blockchain-base",
    "block-production",
    "block-production-albatross",
    "accounts",
    "accounts/tree-primitives",
    "mempool",
    "network-primitives",
    "consensus",
    "network",
    "client",
    "rpc-server",
    "metrics-server",
    "lib",
    "lib2",
    "messages",
    "fixed-unsigned",
    "bls",
    "validator",
    "tools",
    "build-tools",
    "wallet",
    "handel"
]

[profile.dev.overrides.pairing]
opt-level = 3
debug = false

[patch.crates-io]
beserial = { path = "beserial" }
beserial_derive = { path = "beserial/beserial_derive" }
fixed-unsigned = { path = "fixed-unsigned" }
libargon2-sys = { path = "libargon2-sys" }

nimiq-account = { path = "primitives/account" }
nimiq-accounts = { path = "accounts" }
nimiq-block = { path = "primitives/block" }
nimiq-block-base = { path = "primitives/block-base" }
nimiq-block-production = { path = "block-production" }
nimiq-blockchain = { path = "blockchain" }
nimiq-block-albatross = { path = "primitives/block-albatross" }
nimiq-block-production-albatross = { path = "block-production-albatross" }
nimiq-blockchain-albatross = { path = "blockchain-albatross" }
nimiq-blockchain-base = { path = "blockchain-base" }
nimiq-bls = { path = "bls" }
nimiq-build-tools = { path = "build-tools" }
nimiq-collections = { path = "collections" }
nimiq-consensus = { path = "consensus" }
nimiq-database = { path = "database" }
nimiq-handel = { path = "handel" }
nimiq-hash = { path = "hash" }
nimiq-hash_derive = { path = "hash/hash_derive" }
nimiq-keys = { path = "keys" }
nimiq-key-derivation = { path = "key-derivation" }
nimiq-lib = { path = "lib" }
nimiq-lib2 = { path = "lib2" }
nimiq-macros = { path = "macros" }
nimiq-mempool = { path = "mempool" }
nimiq-messages = { path = "messages"}
nimiq-metrics-server = { path = "metrics-server" }
nimiq-network = { path = "network" }
nimiq-network-primitives = { path = "network-primitives" }
nimiq-primitives = { path = "primitives" }
nimiq-rpc-server = { path = "rpc-server" }
nimiq-transaction = { path = "primitives/transaction" }
nimiq-tree-primitives = { path = "accounts/tree-primitives" }
nimiq-utils = { path = "utils" }
nimiq-validator = { path = "validator" }
nimiq-wallet = { path = "wallet" }
