cargo-features = [
  "profile-overrides"
]

[workspace]
members = [
  "accounts",
  "accounts/tree-primitives",
  "beserial",
  "beserial/beserial_derive",
  "block-production-albatross",
  "blockchain-albatross",
  "bls",
  "build-tools",
  "client",
  "collections",
  "consensus-albatross",
  "database",
  "genesis",
  "handel",
  "hash",
  "hash/hash_derive",
  "key-derivation",
  "keys",
  "lib",
  "macros",
  "mempool",
  "messages",
  "metrics-server",
  "mnemonic",
  "nano-sync",
  "network-albatross",
  "network-interface",
  "network-libp2p",
  "network-mock",
  "peer-address",
  "primitives",
  "primitives/account",
  "primitives/block-albatross",
  "primitives/subscription",
  "primitives/transaction",
  "rpc-client",
  "rpc-interface",
  "rpc-server",
  "tendermint",
  "tools",
  "transaction-builder",
  "utils",
  "validator",
  "validator-network",
  "vrf",
  "wallet",
]

[profile.dev.package.nimiq-bls]
opt-level = 3

[profile.dev.package.nimiq-nano-sync]
opt-level = 3

[patch.'https://github.com/nimiq/jsonrpc.git/']
nimiq-jsonrpc-core = { path = "/home/janosch/IntelliJ Projects/nimiq-jsonrpc/nimiq-jsonrpc-core" }
nimiq-jsonrpc-derive = { path = "/home/janosch/IntelliJ Projects/nimiq-jsonrpc/nimiq-jsonrpc-derive" }
nimiq-jsonrpc-client = { path = "/home/janosch/IntelliJ Projects/nimiq-jsonrpc/nimiq-jsonrpc-client" }
nimiq-jsonrpc-server = { path = "/home/janosch/IntelliJ Projects/nimiq-jsonrpc/nimiq-jsonrpc-server" }