
[network]
peer_key_file = "peer_key.dat"
listen_addresses = ["/ip4/127.0.0.1/tcp/8443/ws"]

[rpc-server]
bind = "127.0.0.1"
port = 8648

[log]
level = "debug"

[validator]
validator_address = "NQ07 0000 0000 0000 0000 0000 0000 0000 0000"
voting_key_file = "voting_key.dat"
fee_key_file = "fee_key.dat"
signing_key_file = "signing_key.dat"
