version: "3.5"

networks:
  devnet:
    name: ${NETWORK_NAME:?err}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 7.0.0.0/24

services:
  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.nimiq.address=:8443
      - --entrypoints.rpc.address=:8648
      - --providers.docker=true
    ports:
      - "8443:8443"
      - "8648:8648"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      devnet:
        ipv4_address: 7.0.0.100

  seed1:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed1.rule=Host(`seed1.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed1.entrypoints=nimiq
      - traefik.http.routers.seed1.service=seed1
      - traefik.http.services.seed1.loadbalancer.server.port=8443

      # Accept outside RPC connections
      - traefik.http.routers.seed1-rpc.rule=Host(`seed1.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed1-rpc.entrypoints=rpc
      - traefik.http.routers.seed1-rpc.service=seed1-rpc
      - traefik.http.services.seed1-rpc.loadbalancer.server.port=8648
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.2/tcp/8443/ws
      - NIMIQ_HOST=seed1.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_ADDRESS=NQ20TSB0DFSMUH9C15GQGAGJTTE4D3MA859E
      - SIGNING_KEY=041580cc67e66e9e08b68fd9e4c9deb68737168fbe7488de2638c2e906c2f5ad
      - VOTING_KEY=689bf3a52a07af0c7a0901a17e5d285496bb4b60626f4ebd9365ab05a093998edf28b3bf2cf25bdeb5458a14c2ade928ada0215de265ace57616c5ce4f76991d2f350fb8df796dbb2da4c492817d27a1578e5006b43be2f05b938fb5134f0000
      - FEE_KEY=6c9320ac201caf1f8eaa5b05f5d67a9e77826f3f6be266a0ecccc20416dc6587
      - RPC_ENABLED=true
      # - RPC_USERNAME=rpcclient
      # - RPC_PASSWORD=7F8E0E42-8ACF-47E7-8CC1-0EC66FA3D82D
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=info
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.2
    volumes:
      - "seed1:/home/nimiq/.nimiq:rw"

  seed2:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed2.rule=Host(`seed2.${NETWORK_NAME:?err}`)
    depends_on:
      - seed1
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.3/tcp/8443/ws
      - NIMIQ_HOST=seed2.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_ADDRESS=NQ69MH903M5HDFNU8E8453FXJSY6XYQSN2CE
      - SIGNING_KEY=aed203193d0464f2a584087dd0bd17cca83b831cfd967c238a464a5b9dc30db7
      - VOTING_KEY=640e6da0e6e8e4950f605737a26a1ba9bb2361016b96b3fc0625ec7455fd58e52680b5b7813b07f05ab564017ba2ff34d952d56988995fd51a1027fef2d20bb8d1b1ee1077c6d26b63dca30e632dda84de902d04ad4f59c4db020ac96f2a0000
      - FEE_KEY=6648bedb41bd47e68218e0b0b939e700d42c4f3cb4c70abaa1b76a7ca880d81b
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=info
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.3
    volumes:
      - "seed2:/home/nimiq/.nimiq:rw"

  seed3:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed3.rule=Host(`seed3.${NETWORK_NAME:?err}`)
    depends_on:
      - seed2
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.4/tcp/8443/ws
      - NIMIQ_HOST=seed3.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_ADDRESS=NQ79VVKKSSCGHJUJKFHVEA1YNEJ66P7SST56
      - SIGNING_KEY=fb9313e42037e9acd6105c5a5e1264c5d8df917f9076f26f266051e121c5611b
      - VOTING_KEY=d9c95fbb3421d1e1458eb88a0fe3ff9412d11d6fa63bfd233ab2702a734bd399dc9673273808995a1ae08b8332abdeb1e150c20d386a139edc1c6234de519afb2924ffe3773bcbaf8473925705301b0d94e15bd16e33f6c65720527559a30100
      - FEE_KEY=a436860a1efb3b70a11515720b6afa9a36de2531292183a966babc684a7e8f4e
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=info
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.4
    volumes:
      - "seed3:/home/nimiq/.nimiq:rw"

  seed4:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed4.rule=Host(`seed4.${NETWORK_NAME:?err}`)
    depends_on:
      - seed3
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.5/tcp/8443/ws
      - NIMIQ_HOST=seed4.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      # - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_ADDRESS=NQ83BPY4JPJH5B1YNYKQ32V184L4YU351VTL
      - SIGNING_KEY=973e58d73a7316673c9edf05397accac0123a8111240e1764119211f5a68b7e4
      - VOTING_KEY=1e841644450c987da907510a7a2da0191f568c7163a972a9869770cabf7f025cded86cabc665310718e8e9d24629fcba154b888a970715a4a64bb1a761cf04b8dbe4fcc86c8240d2e5aa62e7b2076ddc2b61ba560d1e5fcc30ecc4b8fb4e0100
      - FEE_KEY=f52865adebd028d36660b1150bde7f73ad8143ac58027023ceb528d57f49ec1c
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=info
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.5
    volumes:
      - "seed4:/home/nimiq/.nimiq:rw"

  seed5:
    image: core:latest
    labels:
      # Accept outside Nimiq protocol connections
      - traefik.http.routers.seed5.rule=Host(`seed5.${NETWORK_NAME:?err}`)

      # Accept outside RPC connections
      - traefik.http.routers.seed5-rpc.rule=Host(`seed5.${NETWORK_NAME:?err}`)
      - traefik.http.routers.seed5-rpc.entrypoints=rpc
      - traefik.http.routers.seed5-rpc.service=seed5-rpc
      - traefik.http.services.seed5-rpc.loadbalancer.server.port=8648

    depends_on:
      - seed4
    environment:
      - LISTEN_ADDRESSES=/ip4/7.0.0.6/tcp/8443/ws
      - NIMIQ_HOST=seed4.${NETWORK_NAME:?err}
      - NIMIQ_NETWORK=dev-albatross
      - NIMIQ_SEED_NODES=/ip4/7.0.0.2/tcp/8443/ws
      - NIMIQ_PEER_KEY_FILE=/home/nimiq/.nimiq/peer_key.dat
      - NIMIQ_INSTANT_INBOUND=true
      - NIMIQ_VALIDATOR=validator
      - NIMIQ_MIN_PEERS=1
      - VALIDATOR_ADDRESS=NQ98RXTFQFRJVJP3CV5EGU8XKKQ6CM6CNF9F #private key: 375f6ba7cae26cccacbe6a75a5ac3f94858426dcb855cfd6536fdcb7fc9206b4
      - RPC_ENABLED=true
      - RUST_BACKTRACE="1"
      - NIMIQ_LOG_LEVEL=info
      - NIMIQ_LOG_TIMESTAMPS=true
    networks:
      devnet:
        ipv4_address: 7.0.0.6
    volumes:
      - "seed5:/home/nimiq/.nimiq:rw"

  # validator1:
  #   image: core
  #   labels:
  #     - traefik.http.routers.validator1.rule=Host(`validator1.${NETWORK_NAME:?err}`)
  #   depends_on:
  #     - seed2
  #   environment:
  #     - NIMIQ_HOST=validator1.${NETWORK_NAME:?err}
  #     - NIMIQ_NETWORK=dev-albatross
  #     - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
  #     - NIMIQ_VALIDATOR=validator
  #     - RPC_ENABLED=true
  #     - RUST_BACKTRACE="1"
  #     - NIMIQ_LOG_LEVEL=debug
  #     - NIMIQ_LOG_TIMESTAMPS=true
  #   networks:
  #     - devnet

  # validator2:
  #   image: core
  #   labels:
  #     - traefik.http.routers.validator2.rule=Host(`validator2.${NETWORK_NAME:?err}`)
  #   depends_on:
  #     - seed2
  #   environment:
  #     - NIMIQ_HOST=validator2.${NETWORK_NAME:?err}
  #     - NIMIQ_NETWORK=dev-albatross
  #     - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
  #     - NIMIQ_VALIDATOR=validator
  #     - RPC_ENABLED=true
  #     - RUST_BACKTRACE="1"
  #     - NIMIQ_LOG_LEVEL=debug
  #     - NIMIQ_LOG_TIMESTAMPS=true
  #   networks:
  #     - devnet

  # validator3:
  #   image: core
  #   labels:
  #     - traefik.http.routers.validator3.rule=Host(`validator3.${NETWORK_NAME:?err}`)
  #   depends_on:
  #     - seed2
  #   environment:
  #     - NIMIQ_HOST=validator3.${NETWORK_NAME:?err}
  #     - NIMIQ_NETWORK=dev-albatross
  #     - NIMIQ_SEED_NODES=ws://seed1.${NETWORK_NAME:?err}:8443/5af4c3f30998573e8d3476cd0e0543bf7adba576ef321342e41c2bccc246c377
  #     - NIMIQ_VALIDATOR=validator
  #     - RPC_ENABLED=true
  #     - RUST_BACKTRACE="1"
  #     - NIMIQ_LOG_LEVEL=debug
  #     - NIMIQ_LOG_TIMESTAMPS=true
  #   networks:
  #     - devnet

  # staking: # Auto staking script (Py)
  #   image: autostaker
  #   restart: always
  #   depends_on:
  #     - validator1
  #   labels:
  #     - traefik.enable=false
  #   environment:
  #     - VALIDATOR_AMOUNT=100000000
  #     - PRIVATE_KEY=b627f21705a095d095327d37ab1c481b40f6cc0fd9c64d0e154919a66a9bb985
  #     - LOG_LEVEL=info
  #     - NETWORK_NAME=${NETWORK_NAME:?err}
  #     - REWARD_ADDRESS="NQ69 UMYS AUH5 UL42 SYFG 55KD S3XP 2PVF YQ6C"
  #     - DOCKER_HOST=unix:/var/run/docker.sock
  #   networks:
  #     devnet:
  #       ipv4_address: 7.0.0.250
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  seed1:
  seed2:
  seed3:
  seed4:
  seed5:
