[[validator]]
restartable = true
sync_mode = "full"

[[validator]]
restartable = true
sync_mode = "full"

[[validator]]
restartable = true
sync_mode = "full"

[[validator]]
restartable = true
sync_mode = "full"

[[seed]]
restartable = false
sync_mode = "history"