[package]
name = "nimiq-block-production-albatross"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "Albatross Block Production logic for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { version = "0.1" }
nimiq-block-albatross = { version = "0.1" }
nimiq-blockchain-albatross = { version = "0.1" }
nimiq-blockchain-base = { version = "0.1" }
nimiq-bls = { version = "0.1" }
nimiq-collections = { version = "0.1" }
nimiq-database = { version = "0.1" }
nimiq-hash = { version = "0.1" }
nimiq-keys = { version = "0.1" }
nimiq-mempool = { version = "0.1" }
nimiq-network-primitives = { version = "0.1", features = ["networks"] }
nimiq-primitives = { version = "0.1" }
log = "0.4"

[dev-dependencies]
hex = "0.3"
nimiq-account = { version = "0.1" }
nimiq-database = { version = "0.1" }
nimiq-transaction = { version = "0.1" }
nimiq-collections = { version = "0.1" }