[package]
name = "nimiq-block-albatross"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Block primitives for Albatross"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
bitflags = "1.0"
thiserror = "1.0"
hex = "0.4"
log = "0.4"
num-bigint = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }

beserial = { path = "../../beserial", version = "0.1" }
beserial_derive = { path = "../../beserial/beserial_derive", version = "0.1" }
nimiq-account = { path = "../account", version = "0.1" }
nimiq-bls = { path = "../../bls", version = "0.1", features = ["beserial"]}
nimiq-collections = { path = "../../collections", version = "0.1", features = ["bitset"] }
nimiq-handel = { path = "../../handel", version = "0.1" }
nimiq-hash = { path = "../../hash", version = "0.1" }
nimiq-hash_derive = { path = "../../hash/hash_derive", version = "0.1" }
nimiq-keys = { path = "../../keys", version = "0.1" }
nimiq-macros = { path = "../../macros", version = "0.1" }
nimiq-nano-sync = { path = "../../nano-sync", version = "0.1" }
nimiq-network-interface = { path = "../../network-interface", version = "0.1" }
nimiq-primitives = { path = "..", version = "0.1", features = ["policy", "networks", "coin"] }
nimiq-transaction = { path = "../transaction", version = "0.1" }
nimiq-utils = { path = "../../utils", version = "0.1", features = ["merkle"] }
nimiq-vrf = { path = "../../vrf", version = "0.1" }

[dev-dependencies]
num-traits = "0.2"

[features]
serde-derive = ["serde", "nimiq-collections/serde-derive", "nimiq-bls/serde-derive"]
