[package]
name = "nimiq-block-albatross"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Block primitives for Albatross"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
hex = "0.3"
log = "0.4"
num-bigint = "0.2"
failure = "0.1"
beserial = "0.1"
beserial_derive = "0.1"
fixed-unsigned = "0.1"
nimiq-account = "0.1"
nimiq-block-base = "0.1"
nimiq-bls = { version = "0.1", features = ["beserial"]}
nimiq-collections = { version = "0.1", features = ["bitset"] }
nimiq-hash = "0.1"
nimiq-hash_derive = "0.1"
nimiq-keys = "0.1"
nimiq-macros = "0.1"
nimiq-primitives = { version = "0.1", features = ["policy", "networks"] }
nimiq-transaction = "0.1"
nimiq-utils = { version = "0.1", features = ["merkle"] }

[dev-dependencies]
num-traits = "0.2"
