[package]
name = "nimiq-wallet"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Wallet logic for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
serde = "1.0"

nimiq-database = { path = "../database" }
nimiq-database-value = { path = "../database/database-value" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives" }
nimiq-serde = { path = "../serde" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-utils = { path = "../utils", features = ["otp"]}

[dev-dependencies]
hex = "0.4"
nimiq-test-log = { path = "../test-log" }
