[package]
name = "nimiq-wallet"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Wallet logic for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../beserial", version = "0.1" }
nimiq-account = { path = "../primitives/account", version = "0.1" }
nimiq-keys = { path = "../keys", version = "0.1" }
nimiq-key-derivation = { path = "../key-derivation", version = "0.1" }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-primitives = { path = "../primitives", version = "0.1" }
nimiq-transaction = { path = "../primitives/transaction", version = "0.1" }
nimiq-database = { path = "../database", version = "0.1" }
failure = "0.1"
log = "0.4"
hex = "0.3"
