[package]
name = "nimiq-wallet"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Wallet logic for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { version = "0.1" }
beserial_derive = { version = "0.1" }
nimiq-account = { version = "0.1" }
nimiq-keys = { version = "0.1" }
nimiq-key-derivation = { version = "0.1" }
nimiq-hash = { version = "0.1" }
nimiq-primitives = { version = "0.1" }
nimiq-transaction = { version = "0.1" }
nimiq-database = { version = "0.1", features = ["keys"] }
nimiq-utils = { version = "0.1", features = ["otp"]}
failure = "0.1"
hex = "0.3"

[dev-dependencies]
lazy_static = "1.3"