[[validator]]
restartable = true
sync_mode = "history"

[[validator]]
restartable = true
sync_mode = "history"

[[validator]]
restartable = true
sync_mode = "history"

[[validator]]
restartable = true
sync_mode = "history"

[[spammer]]
restartable = false
sync_mode = "history"
tpb = 500

[[seed]]
restartable = false
sync_mode = "history"
