[package]
name = "nimiq-build-tools"
version = "0.1.0"
authors = ["Janosch Gräf <janosch@nimiq.com>"]
edition = "2018"

[[bin]]
name = "nimiq-genesis"
path = "src/genesis/main.rs"

[[bin]]
name = "nimiq-devnet"
path = "src/devnet/main.rs"

[dependencies]
nimiq-bls = { path = "../bls", optional = true }
nimiq-block = { path = "../primitives/block", optional = true }
nimiq-block-albatross = { path = "../primitives/block-albatross", optional = true }
nimiq-collections = { path = "../collections" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives" }
nimiq-account = { path = "../primitives/account" }
nimiq-accounts = { path = "../accounts" }
nimiq-database = { path = "../database", features = ["account"] }
beserial = { path = "../beserial" }
lazy_static = "1.3"
rand = "0.6"
rand04_compat = "0.1"
rand_chacha = "0.1"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
hex = "0.3"
log = "0.4"
simple_logger = "1.0"
failure = "0.1"
structopt = { version = "0.2", features = ["paw"] }
paw = "1.0"
shellfn = "0.1"
ctrlc = "3.1"

[features]
default = ["albatross", "powchain"]
albatross = ["nimiq-bls", "nimiq-block-albatross"]
powchain = ["nimiq-block"]