[package]
name = "nimiq-validator"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Validator logic of Albatross"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../beserial" }
nimiq-account = { path = "../primitives/account" }
nimiq-bls = { path = "../bls" }
nimiq-consensus = { path = "../consensus" }
nimiq-collections = { path = "../collections", features = ["bitset"] }
nimiq-database = { path = "../database", features = ["full-nimiq"] }
nimiq-macros = { path = "../macros" }
nimiq-mempool = { path = "../mempool" }
nimiq-network = { path = "../network" }
nimiq-network-primitives = { path = "../network-primitives", features = ["networks", "time"] }
nimiq-utils = { path = "../utils", features = ["observer", "timers", "mutable-once", "throttled-queue", "rate-limit"] }
nimiq-block-albatross = { path = "../primitives/block-albatross" }
nimiq-messages = { path = "../messages" }
nimiq-hash = { path = "../hash" }
nimiq-primitives = { path = "../primitives" }
nimiq-blockchain-albatross = { path = "../blockchain-albatross" }
nimiq-block-production-albatross = { path = "../block-production-albatross" }
nimiq-blockchain-base = { path = "../blockchain-base" }
nimiq-handel = { path = "../handel", version = "0.1", optional = true}
hex = { version = "0.3", optional = true }
failure = "0.1"
log = "0.4"
parking_lot = "0.7"
rand = "0.6"

[features]
default = ["handel"] # for now enable by default
metrics = []
mock = ["hex"]
handel = ["nimiq-handel", "nimiq-messages/handel"]
