[package]
name = "nimiq-validator"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Validator logic of Albatross"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { version = "0.1" }
nimiq-account = { version = "0.1" }
nimiq-bls = { version = "0.1" }
nimiq-consensus = { version = "0.1" }
nimiq-collections = { version = "0.1", features = ["bitset"] }
nimiq-database = { version = "0.1", features = ["full-nimiq"] }
nimiq-macros = { version = "0.1" }
nimiq-mempool = { version = "0.1" }
nimiq-network = { version = "0.1" }
nimiq-network-primitives = { version = "0.1", features = ["networks", "time"] }
nimiq-utils = { version = "0.1", features = ["observer", "timers", "mutable-once", "throttled-queue", "rate-limit"] }
nimiq-block-albatross = { version = "0.1" }
nimiq-messages = { version = "0.1" }
nimiq-hash = { version = "0.1" }
nimiq-primitives = { version = "0.1" }
nimiq-blockchain-albatross = { version = "0.1" }
nimiq-block-production-albatross = { version = "0.1" }
nimiq-blockchain-base = { version = "0.1" }
nimiq-handel = { version = "0.1" }
hex = { version = "0.3", optional = true }
failure = "0.1"
log = "0.4"
parking_lot = "0.9"
rand = "0.6"
tokio = "0.1"
futures = "0.1"

[features]
metrics = []
