[package]
name = "nimiq-validator"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Validator logic of Albatross"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = "0.1"
nimiq-account = "0.1"
nimiq-bls = "0.1"
nimiq-consensus = "0.1"
nimiq-collections = { version = "0.1", features = ["bitset"] }
nimiq-database = { version = "0.1", features = ["full-nimiq"] }
nimiq-macros = "0.1"
nimiq-mempool = "0.1"
nimiq-network = "0.1"
nimiq-network-primitives = { version = "0.1", features = ["networks", "time"] }
nimiq-utils = { version = "0.1", features = ["observer", "timers", "mutable-once", "throttled-queue", "rate-limit"] }
nimiq-block-albatross = "0.1"
nimiq-messages = "0.1"
nimiq-hash = "0.1"
nimiq-primitives = "0.1"
nimiq-blockchain-albatross = "0.1"
nimiq-block-production-albatross = "0.1"
nimiq-blockchain-base = "0.1"
nimiq-handel = "0.1"
hex = { version = "0.4", optional = true }
failure = "0.1"
log = "0.4"
parking_lot = "0.9"
rand = "0.7"
tokio = "0.1"
futures = "0.1"

[features]
metrics = []
