[package]
name = "nimiq-validator-network"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq's validator network abstraction in Rust"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
async-trait = "0.1"
beserial = { path = "../beserial", version = "0.1", features = ["libp2p"] }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.1" }
futures = "0.3"
thiserror = "1.0"
log = "0.4"

nimiq-network-interface = { path = "../network-interface", version = "0.1" }
nimiq-bls = { path = "../bls", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1" }

[dev-dependencies]
nimiq-network-mock = { path = "../network-mock", version = "0.1" }
