[package]
name = "nimiq-network-interface"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq's network implementation in Rust"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
async-trait = "0.1"
bitflags = "1.2"
futures = { package = "futures-util", version = "0.3" }
libp2p = { git = "https://github.com/jsdanielh/rust-libp2p.git", default-features = false }
log = { package = "tracing", version = "0.1", features = ["log"] }
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1.29", features = ["rt"] }
tokio-stream = { version = "0.1", features = ["default", "sync"] }

nimiq-serde = { workspace = true }

[dev-dependencies]
nimiq-test-log = { workspace = true }
