[network]
peer_key_file = "/home/nimiq/peer_key.dat"
listen_addresses = [
    "/ip4/0.0.0.0/tcp/8443/ws",
]
advertised_addresses = [
    "/dns4/validator3/tcp/8443/ws", # Docker-internal
    "/dns4/validator3.webauthn.pos.nimiqwatch.com/tcp/443/wss" # Docker-external
]

seed_nodes = [
        { address = "/dns4/seed1/tcp/8443/ws" }
]

[consensus]
network = "dev-albatross"
sync_mode = "history"
min_peers = 3

[database]
path = "/home/nimiq"

[log]
level = "info"
timestamps = true

# [log.tags]
# libp2p_swarm = "debug"
# lock_api = "trace"

[validator]
validator_address = "NQ55 0A8E PP1X SBEP BY6L Y1BM K492 6U0D 73MS"
signing_key_file = "/home/nimiq/signing_key.dat"
signing_key = "604a958929b882a603a50128aeced5c6b523dde0fdd7a20e99a1f87e48feba07"
voting_key_file = "/home/nimiq/voting_key.dat"
voting_key = "56399deebbbe0b0d2b990d3f563ea47e58c0e5f0cca942bd82ff1c54a4f84e687a73a268910b0ba988268ead5db1f131be783a414eb6e8aa907b8a93a01a10ed726087706ca10017ec8439d32aa96e24c76d0e2175228d8b7a965e84fd2a01"
fee_key_file = "/home/nimiq/fee_key.dat"
fee_key = "59f14c957cbe09712dc6fd1c5243e29909ac69014bfd588b660b15e4e05709eb"
