[network]
peer_key_file = "/home/nimiq/peer_key.dat"
listen_addresses = [
    "/ip4/0.0.0.0/tcp/8443/ws",
]
advertised_addresses = [
    "/dns4/validator3/tcp/8443/ws", # Docker-internal
    "/dns4/validator3.nimiq.local/tcp/8503/ws" # Docker-external
]

seed_nodes = [
        { address = "/dns4/seed1/tcp/8443/ws" }
]

[consensus]
network = "dev-albatross"
sync_mode = "history"
min_peers = 3

[database]
path = "/home/nimiq"

[log]
level = "info"
timestamps = true

# [log.tags]
# libp2p_swarm = "debug"
# lock_api = "trace"

[validator]
validator_address = "NQ17 XPA3 LT7K UN34 Y9YQ 30VQ G54G 1G3Q BLYB"
signing_key_file = "/home/nimiq/signing_key.dat"
signing_key = "8c99b8b0784835e869d3a88759429014935607411c752e4c0f13c34eed7e787a"
voting_key_file = "/home/nimiq/voting_key.dat"
voting_key = "e8aea9fb49e7ecf87713101bec5fa81155dec6a09f9ff9b8bf3572f1132eab631172fc1a706faa0b0cfa34c5fa8903a98f259131a4476eb269f7ac376569e184332de6be5a5dac65c1a16832604b23fc4ba7d83a0bf9d45b1a4bf0c37f1001"
fee_key_file = "/home/nimiq/fee_key.dat"
fee_key = "a1d348e15ee7174791b3610a2ac7a700738a5e44b4fd9f5807d1cf68fbee43ba"
