[package]
name = "nimiq-network-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Network primitives and constants for Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]
build = "build.rs"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
bitflags = "1.0"
hex = "0.3"
lazy_static = "1.2"
atomic = "0.4"
url = "1.7"
failure = "0.1"
beserial = { path = "../beserial", features = ["net"] }
beserial_derive = { path = "../beserial/beserial_derive"}
nimiq-keys = { path = "../keys" }
nimiq-hash = { path = "../hash" }
nimiq-hash_derive = { path = "../hash/hash_derive" }
nimiq-block = { path = "../primitives/block", version = "0.1" }
nimiq-block-albatross = { path = "../primitives/block-albatross" }
nimiq-bls = { path = "../bls" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-primitives = { path = "../primitives", features = ["coin", "networks"] }
nimiq-account = { path = "../primitives/account" }
nimiq-utils = { path = "../utils", features = ["observer", "crc", "time"] }
nimiq-macros = { path = "../macros" }

[build-dependencies]
nimiq-build-tools = { path = "../build-tools" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
human-panic = { version = "1.0" }
log = "0.4"
simple_logger = "1.0"

[features]
default = ["all"]
all = ["networks", "time", "address", "services", "version", "protocol", "subscription", "validator"]
networks = ["address", "services", "protocol"]
time = []
address = ["services", "protocol"]
services = []
version = []
protocol = []
subscription = []
validator = []
