[package]
name = "network-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
keys = { path = "../keys" }
hash = { path = "../hash" }
primitives = { path = "../primitives", features = ["account", "block", "transaction"] }
utils = { path = "../utils", features = ["observer", "crc", "time"] }
macros = { path = "../macros" }
bitflags = "1.0"
log = "0.4.3"
rand = "0.6.4"
parking_lot = "0.6"
byteorder = "1.2"
hex = "0.3.2"
lazy_static = "1.0"
atomic = "0.4"

[features]
all = ["message", "networks", "time", "address", "services", "version", "protocol", "subscription"]
message = ["address", "protocol", "subscription", "services", "version"]
networks = ["address", "services", "protocol"]
time = []
address = ["services", "protocol"]
services = []
version = []
protocol = []
subscription = []
