[package]
name = "nimiq-network-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Network primitives and constants for Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
nimiq-keys = { path = "../keys" }
nimiq-hash = { path = "../hash" }
nimiq-account = { path = "../primitives/account" }
nimiq-block = { path = "../primitives/block" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-primitives = { path = "../primitives", features = ["coin", "networks"] }
nimiq-utils = { path = "../utils", features = ["observer", "crc", "time"] }
nimiq-macros = { path = "../macros" }
bitflags = "1.0"
rand = "0.6.4"
parking_lot = "0.6"
byteorder = "1.2"
hex = "0.3.2"
lazy_static = "1.0"
atomic = "0.4"

[features]
all = ["networks", "time", "address", "services", "version", "protocol", "subscription"]
networks = ["address", "services", "protocol"]
time = []
address = ["services", "protocol"]
services = []
version = []
protocol = []
subscription = []
