[package]
name = "nimiq-hash"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Common wrapper around hash implementations used in Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
blake2-rfc = "0.2"
libargon2-sys = { path = "../libargon2-sys" }
hex = "0.3"
sha2 = "0.8"
beserial = { path = "../beserial" }
nimiq-macros = { path = "../macros" }
byteorder = "1.2"