[package]
name = "nimiq-mmr"
version.workspace = true
authors = ["Pascal Berrang <contact@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
license.workspace = true
edition.workspace = true
description = "Merkle Mountain Range primitive for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
serde = { version = "1.0", optional = true }

nimiq-serde = { path = "../../serde", optional = true }

[dev-dependencies]
nimiq-test-log = { path = "../../test-log" }

[features]
serde-derive = ["nimiq-serde", "serde"]
