[package]
name = "beserial_derive"
version = "0.1.0"
authors = ["Marvin W <git@larma.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
beserial = { path = ".." }
