[package]
name = "nimiq-handel"
version = "0.1.0"
authors = ["Janosch Gräf <janosch@nimiq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beserial = "0.1"
beserial_derive = "0.1"
nimiq-bls = "0.1"
nimiq-collections = { version = "0.1", features = ["bitset"] }
nimiq-hash = "0.1"
nimiq-utils = { version = "0.1", features = ["math", "mutable-once", "observer", "timers"] }
nimiq-macros = "0.1"
futures = "0.1"
futures-cpupool = "0.1"
stopwatch = "0.0"
failure = "0.1"
log = "0.4"
tokio = "0.1"
rand = "0.7"
parking_lot = "0.9"
lazy_static = "1.3"


[dev-dependencies]
hex = "0.4"
