[package]
name = "nimiq-network"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq's network implementation in Rust"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
nimiq-blockchain = { path = "../blockchain" }
nimiq-collections = { path = "../collections" }
nimiq-keys = { path = "../keys" }
nimiq-hash = { path = "../hash" }
nimiq-macros = { path = "../macros" }
nimiq-messages = { path = "../messages" }
nimiq-network-primitives = { path = "../network-primitives", features = ["all"] }
nimiq-utils = { path = "../utils", features = ["timers", "observer", "mutable-once", "time", "unique-ptr", "iterators", "locking", "rate-limit", "unique-id"] }

atomic = "0.4"
failure = "0.1.5"
failure_derive = "0.1.5"
futures = "0.1"
hex = "0.3.2"
log = "0.4.3"
native-tls = "0.2"
parking_lot = "0.6"
rand = "0.6.4"
reqwest = "0.9.9"
tokio = "0.1"
tokio-tls = "0.2"
tokio-tungstenite = { git = "https://github.com/snapview/tokio-tungstenite", rev = "203fa0b2bd1874a7022e4cf3eae7df75eee30c67" }
url = "1.7"

[dependencies.tungstenite]
# Uncomment when `tungstenite-rs` is released.
# version = "0.7.0"
git = "https://github.com/snapview/tungstenite-rs"
branch = "close-as-message"
default-features = false

[features]
metrics = []
