[package]
name = "nimiq-network"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq's network implementation in Rust"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../beserial" }
nimiq-blockchain = { path = "../blockchain" }
nimiq-keys = { path = "../keys" }
nimiq-hash = { path = "../hash" }
nimiq-macros = { path = "../macros" }
nimiq-messages = { path = "../messages" }
nimiq-network-primitives = { path = "../network-primitives", features = ["all"] }
nimiq-utils = { path = "../utils", features = ["timers", "observer", "mutable-once", "time", "unique-ptr", "iterators", "locking", "rate-limit"] }
atomic = "0.4"
parking_lot = "0.6"
rand = "0.6.4"
log = "0.4.3"

url = "1.7"
tokio = "0.1"
tokio-tls = "0.2"
native-tls = "0.2"
futures = "0.1"
tungstenite = "0.6"
tokio-tungstenite = { git = "https://github.com/jeffesquivels/tokio-tungstenite", branch = "implement_peer_addr" }

[features]
metrics = []
