[package]
name = "nimiq-database-value"
version = "0.1.0"
authors = ["JD Hernandez <jd@nimiq.com>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2021"
description = "A simple trait for writing and reading from a Nimiq DB"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
log = { package = "tracing", version = "0.1", features = ["log"] }
