[package]
name = "nimiq-nano-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
license = "MIT/Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2018"

[dependencies]
ark-ec = { git = "https://github.com/arkworks-rs/algebra" }
ark-mnt4-753 = { git = "https://github.com/arkworks-rs/curves" }
ark-mnt6-753 = { git = "https://github.com/arkworks-rs/curves" }

nimiq-bls = { path = "../bls", version = "0.1" }
