[package]
name = "nimiq-nano-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
license = "MIT/Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2018"

[dependencies]
ark-std = { git = "https://github.com/arkworks-rs/utils" }
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
ark-ec = { git = "https://github.com/arkworks-rs/algebra" }
ark-relations = { git = "https://github.com/arkworks-rs/snark" }
ark-mnt4-753 = { git = "https://github.com/arkworks-rs/curves", features = ["r1cs"] }
ark-mnt6-753 = { git = "https://github.com/arkworks-rs/curves", features = ["r1cs"] }
ark-crypto-primitives = { git = "https://github.com/arkworks-rs/crypto-primitives", branch = "main", features = ["r1cs"] }
ark-r1cs-std = { git = "https://github.com/arkworks-rs/r1cs-std" }
ark-groth16 = { git = "https://github.com/arkworks-rs/groth16", features = ["r1cs"] }

nimiq-bls = { path = "../bls", version = "0.1" }
