[package]
name = "nimiq-transaction-builder"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Wallet logic for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
serde = { version = "1.0", optional = true }
thiserror = "1.0"

nimiq-bls = { path = "../bls" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives" }
nimiq-serde = { path = "../serde" }
nimiq-transaction = { path = "../primitives/transaction" }

[dev-dependencies]
hex = "0.4"
rand = "0.8"

nimiq-test-log = { path = "../test-log" }
nimiq-utils = { path = "../utils", features = ["otp", "key-rng"]}


[features]
serde-derive = ["serde", "nimiq-primitives/serde-derive"]
