[package]
name = "nimiq-tree-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Accounts tree primitives for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../../beserial" }
beserial_derive = { path = "../../beserial/beserial_derive"}
nimiq-keys = { path = "../../keys" }
nimiq-hash = { path = "../../hash" }
hex = "0.3"
nimiq-account = { path = "../../primitives/account" }

[dev-dependencies]
nimiq-primitives = { path = "../../primitives", features = ["coin"] }
