[package]
name = "nimiq-database"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "A LMDB database wrapper with support for volatile storage"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }

[dependencies]
log = "0.4.3"
lmdb-zero = "0.4.4"
fs2 = "0.4.3"
parking_lot = "0.6"
tempdir = "0.3"
rand = "0.6.4"
bitflags = "1.0"
beserial = { path = "../beserial" }
nimiq-hash = { path = "../hash", optional = true }
nimiq-keys = { path = "../keys", optional = true }
nimiq-primitives = { path = "../primitives", optional = true, features = ["block"] }

[features]
# Compiles this package with all features needed for the nimiq client.
full-nimiq = ["hash", "primitives", "keys"]
hash = ["nimiq-hash"]
primitives = ["nimiq-primitives"]
keys = ["nimiq-keys"]
