[package]
name = "key-derivation"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>"]
edition = "2018"

[dependencies]
regex = "1"
byteorder = "1.2"
beserial = { path = "../beserial" }
hash = { path = "../hash" }
keys = { path = "../keys" }

[dev-dependencies]
hex = "0.3.2"
