[package]
name = "nimiq-key-derivation"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Helper library for key derivation in Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }

[dependencies]
regex = "1"
byteorder = "1.2"
beserial = { path = "../beserial" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }

[dev-dependencies]
hex = "0.3.2"
