[package]
name = "nimiq-messages"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Messages send over the nimiq network"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
nimiq-accounts = { path = "../accounts" }
nimiq-blockchain = { path = "../blockchain" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-macros = { path = "../macros" }
nimiq-network-primitives = { path = "../network-primitives", features = ["networks", "subscription", "version"] }
nimiq-primitives = { path = "../primitives", features = ["account", "block", "transaction"] }
nimiq-utils = { path = "../utils", features = ["observer", "crc", "time"] }

bitflags = "1.0"
byteorder = "1.2"
hex = "0.3.2"
log = "0.4.3"
lazy_static = "1.0"
parking_lot = "0.6"
rand = "0.6.4"

[dev-dependencies.nimiq-utils]
path = "../utils"
features = ["observer", "crc", "time", "iterators"]