[package]
name = "nimiq-messages"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Messages send over the nimiq network"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-macros = { path = "../macros" }
nimiq-network-primitives = { path = "../network-primitives", features = ["networks", "subscription", "version"] }
nimiq-tree-primitives = { path = "../accounts/tree-primitives" }
nimiq-block = { path = "../primitives/block" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-utils = { path = "../utils", features = ["observer", "crc", "time"] }
bitflags = "1.0"
byteorder = "1.2"
hex = "0.3"
parking_lot = "0.7"
rand = "0.6"
enum-display-derive = "0.1"

[dev-dependencies.nimiq-utils]
path = "../utils"
features = ["observer", "crc", "time", "iterators"]