[package]
name = "nimiq-messages"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Messages send over the nimiq network"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
bitflags = "1.0"
bitvec = "0.15"
byteorder = "1.2"
hex = "0.4"
log = "0.4"
parking_lot = "0.9"
rand = "0.7"
enum-display-derive = "0.1"
beserial = "0.1"
beserial_derive = "0.1"
nimiq-block = "0.1"
nimiq-block-albatross = "0.1"
nimiq-block-base = "0.1"
nimiq-bls = "0.1"
nimiq-hash = "0.1"
nimiq-keys = "0.1"
nimiq-macros = "0.1"
nimiq-network-primitives = { version = "0.1", features = ["networks", "subscription", "version"] }
nimiq-tree-primitives = "0.1"
nimiq-transaction = "0.1"
nimiq-account = "0.1"
nimiq-utils = { version = "0.1", features = ["observer", "crc", "time"] }
nimiq-handel = "0.1"

[dev-dependencies]
nimiq-utils = { version = "0.1", features = ["observer", "crc", "time", "iterators"] }
