[network]
peer_key_file = ".nimiq/keys/peer_key.dat"
listen_addresses = ["/ip4/127.0.0.1/tcp/8443/ws"]
seed_nodes = [
        { address = "/ip4/127.0.0.1/tcp/8443/ws" }
]

[consensus]
network = "unit-albatross"
min_peers = 0

[database]
path=".nimiq"

[rpc-server]
bind = "127.0.0.1"
port = 8648

[log]
level = "trace"
timestamps = true

[log.tags]
libp2p_swarm = "debug"
lock_api = "trace"

[validator]
signing_key_file = ".nimiq/keys/signing_key.dat"
voting_key_file = ".nimiq/keys/voting_key.dat"
fee_key_file = ".nimiq/keys/fee_key.dat"
fee_key = "6c9320ac201caf1f8eaa5b05f5d67a9e77826f3f6be266a0ecccc20416dc6587"

validator_address = "NQ20 TSB0 DFSM UH9C 15GQ GAGJ TTE4 D3MA 859E"
signing_key = "041580cc67e66e9e08b68fd9e4c9deb68737168fbe7488de2638c2e906c2f5ad"
voting_key = "196ffdb1a8acc7cbd76a251aeac0600a1d68b3aba1eba823b5e4dc5dbdcdc730afa752c05ab4f6ef8518384ad514f403c5a088a22b17bf1bc14f8ff8decc2a512c0a200f68d7bdf5a319b30356fe8d1d75ef510aed7a8660968c216c328a0000"
