[package]
name = "libargon2-sys"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
links = "argon2"
build = "build.rs"

[dependencies]
libc = "0.2"
[build-dependencies]
gcc = "0.3"
