[package]
name = "nimiq-mnemonic"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>"]
edition = "2018"

[dependencies]
nimiq-hash = { path = "../hash" }
beserial = { path = "../beserial" }
nimiq-macros = { path = "../macros" }
nimiq-utils = { path = "../utils", features = ["bit-vec", "crc"] }
bit-vec = "0.5.0"
hex = "0.3.2"
nimiq-key-derivation = { path = "../key-derivation", optional = true }
unicode-normalization = "0.1.7"
