[package]
name = "nimiq-mnemonic"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Mnemonic helper library for Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }

[dependencies]
nimiq-hash = { path = "../hash" }
beserial = { path = "../beserial" }
nimiq-macros = { path = "../macros" }
nimiq-utils = { path = "../utils", features = ["bit-vec", "crc"] }
bit-vec = "0.5"
hex = "0.3"
nimiq-key-derivation = { path = "../key-derivation", optional = true }
unicode-normalization = "0.1"

[features]
default = ["key-derivation"]
key-derivation = ["nimiq-key-derivation"]