[package]
name = "nimiq-zkp-test-gen"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "All functionality related to the zk proof storage, dissemination and request handeling."
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
hex = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
parking_lot = "0.12"
serde = "1.0"
tracing-subscriber = { version = "0.3" }
tokio = { version = "1.29", features = ["macros", "rt", "sync"] }

nimiq-block = { path = "../../primitives/block" }
nimiq-block-production = { path = "../../block-production" }
nimiq-blockchain = { path = "../../blockchain" }
nimiq-blockchain-interface = { path = "../../blockchain-interface" }
nimiq-blockchain-proxy = { path = "../../blockchain-proxy" }
nimiq-database = { path = "../../database" }
nimiq-genesis = { path = "../../genesis" }
nimiq-log = { path = "../../log" }
nimiq-primitives = { path = "../../primitives", features = ["policy"] }
nimiq-serde = { path = "../../serde" }
nimiq-test-utils = { path = "../../test-utils" }
nimiq-utils = { path = "../../utils", features = [
    "time",
] }
nimiq-zkp = { path = "../../zkp", features = ["zkp-prover"] }
nimiq-zkp-circuits = { path = "../../zkp-circuits", features = ["zkp-prover"] }
nimiq-zkp-component = { path = "..", features = ["zkp-prover"] }
nimiq-zkp-primitives = { path = "../../zkp-primitives", features = ["zkp-prover"] }
