[package]
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Verifiable Random functions based on BLS12-381 signatures"
documentation = "https://github.com/nimiq/core-rs-albatross"
homepage = "https://github.com/nimiq/core-rs-albatross"
license = "MIT/Apache-2.0"
name = "nimiq-vrf"
repository = "https://github.com/nimiq/core-rs-albatross"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.3"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }

beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive" }
nimiq-bls = { path = "../bls", features = ["beserial"]}
nimiq-hash = { path = "../hash" }

[features]
serde-derive = ["serde", "nimiq-bls/serde-derive"]
