[package]
name = "nimiq-vrf"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Verifiable Random Function based on VXEdDSA"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
byteorder = "1.3"
curve25519-dalek = "3"
hex = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
num-traits = "0.2"
rand = "0.8"
serde = { version = "1.0", optional = true }
sha2 = "0.9"

nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-macros = { path = "../macros" }
nimiq-serde = { path = "../serde", optional = true }

[dev-dependencies]
nimiq-test-log = { path = "../test-log" }
nimiq-test-utils = { path = "../test-utils" }

[features]
serde-derive = ["nimiq-serde", "serde"]
