[package]
name = "mempool"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.6"
log = "0.4.3"
beserial = { path = "../beserial" }
hash = { path = "../hash" }
keys = { path = "../keys" }
primitives = { path = "../primitives" }
utils = { path = "../utils", features = ["observer", "timers", "mutable-once"] }
accounts = { path = "../accounts" }
blockchain = { path = "../blockchain" }

[dev-dependencies]
database = { path = "../database" }
network-primitives = { path = "../network-primitives" }
hex = "0.3.2"