[package]
name = "nimiq-mempool"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.6"
log = "0.4.3"
beserial = { path = "../beserial" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives" }
nimiq-utils = { path = "../utils", features = ["observer", "timers", "mutable-once"] }
nimiq-accounts = { path = "../accounts" }
nimiq-blockchain = { path = "../blockchain" }

[dev-dependencies]
nimiq-database = { path = "../database" }
nimiq-network-primitives = { path = "../network-primitives" }
hex = "0.3.2"