[package]
name = "nimiq-mempool"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Mempool implementation for Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
log = "0.4"
parking_lot = "0.9"
beserial = "0.1"
nimiq-account = "0.1"
nimiq-block-base = "0.1"
nimiq-blockchain-base = "0.1"
nimiq-collections = "0.1"
nimiq-hash = "0.1"
nimiq-keys = "0.1"
nimiq-primitives = { version = "0.1", features = ["coin", "networks"] }
nimiq-transaction = "0.1"
nimiq-utils = { version = "0.1", features = ["observer", "timers", "mutable-once"] }

[dev-dependencies]
hex = "0.4"
nimiq-block = "0.1"
nimiq-blockchain = "0.1"
nimiq-database = "0.1"
nimiq-network-primitives = "0.1"
