version: '3.7'
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.42.0/24
services:
  validator-00:
    build: ./
    environment:
     - NIMIQ_HOST=validator-00.devnet
     - EVENTS_EXCHANGE=validator-00
     - NIMIQ_PEER_KEY=8fc065dd2aa0f77753dd8ae86c6ed939881114f43319e6abf42b2ac4759cb46462a1985e85ed3452428d7d29623c1a55d8edc054945b3ed7d512f8487fd88063
     - VALIDATOR_KEY=49ea68eb6b8afdf4ca4d4c0a0b295c76ca85225293693bc30e755476492b707f
    env_file:
     - validator.env
    ports:
     - "8649:8648"
    restart: unless-stopped
    networks:
      default:
        aliases: ["validator-00.devnet"]
  validator-01:
    build: ./
    environment:
      - NIMIQ_HOST=validator-01.devnet
      - EVENTS_EXCHANGE=validator-01
      - VALIDATOR_KEY=2c24c1710667a57f598bff74704b0ea8418ed170389b93ea9f4c91e673d8918d
    env_file:
      - validator.env
    networks:
      default:
        aliases: ["validator-01.devnet"]
    depends_on:
      - validator-00
    restart: unless-stopped