[package]
name = "nimiq-tendermint"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Tendermint implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
futures = "0.3"
log = "0.4"
parking_lot = "0.9"
tokio = { version = "0.2", features = ["rt-core", "sync"] }

async-trait = "0.1"

beserial = { path = "../beserial", version = "0.1" }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.1" }
nimiq-macros = { path = "../macros", version = "0.1" }
nimiq-network-interface = { path = "../network-interface", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1", features = ["observer", "time", "timers", "mutable-once", "throttled-queue", "rate-limit"] }

[dev-dependencies]
nimiq-network-mock = { path = "../network-mock", version = "0.1" }
