[package]
name = "nimiq-tendermint"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Tendermint implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
futures = "0.3"
async-stream = "0.3.0"
async-trait = "0.1"

nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-primitives = { path = "../primitives", version = "0.1", features = ["policy"] }

[dev-dependencies]
nimiq-network-mock = { path = "../network-mock", version = "0.1" }
