[package]
name = "nimiq-tendermint"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Tendermint implementation for Nimiq's Albatross"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
futures = { package = "futures-util", version = "0.3" }
log = { package = "tracing", version = "0.1", features = ["log"] }
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1.29", features = [
    "macros",
    "rt-multi-thread",
    "tracing",
] }
tokio-stream = "0.1"

nimiq-block = { workspace = true }
nimiq-collections = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-macros = { workspace = true }
nimiq-primitives = { workspace = true, features = ["policy"] }

[dev-dependencies]
nimiq-test-log = { workspace = true }
tokio = { version = "1.29", features = [
    "macros",
    "rt-multi-thread",
    "tracing",
] }
tokio-util = "0.7"
