[package]
name = "nimiq-block-base"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Common block traits for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../../beserial", version = "0.1" }
nimiq-hash = { path = "../../hash", version = "0.1" }
nimiq-transaction = { path = "../transaction", version = "0.1" }
failure = "0.1"

[dev-dependencies]
num-traits = "0.2"
