[package]
name = "nimiq-blockchain-base"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Common blockchain types for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
failure = "0.1"
parking_lot = "0.7"
beserial = { path = "../beserial", version = "0.1.0" }
nimiq-account = { path = "../primitives/account", version = "0.1.0" }
nimiq-block-base = { path = "../primitives/block-base", version = "0.1.0" }
nimiq-database = { path = "../database", version = "0.1.0" }
nimiq-hash = { path = "../hash", version = "0.1.0" }
nimiq-keys = { path = "../keys", version = "0.1.0" }
nimiq-network-primitives = { path = "../network-primitives", version = "0.1.0" }
nimiq-primitives = { path = "../primitives", version = "0.1.0" }
nimiq-transaction = { path = "../primitives/transaction", version = "0.1.0" }
nimiq-tree-primitives = { path = "../accounts/tree-primitives", version = "0.1.0" }
nimiq-utils = { path = "../utils", version = "0.1.0", features = ["observer"] }

[features]
metrics = []