[package]
name = "nimiq-zkp"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Recursive SNARKs for Nimiq's Nano Nodes"
license = "Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2021"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[build-dependencies]
ark-serialize = "0.3"
nimiq-zkp-primitives = { path = "../zkp-primitives", features = ["zkp-prover"] }
nimiq-zkp-circuits = { path = "../zkp-circuits", features = ["zkp-prover"] }

[dependencies]
beserial = { path = "../beserial", features = ["derive"]}
lazy_static = {version = "1.4"}
log = { package = "tracing", version = "0.1", features = ["log"] }
rand = { version = "0.8", features = ["small_rng"] }
thiserror = "1.0"

ark-crypto-primitives = "0.3"
ark-ec = "0.3"
ark-ff = "0.3"
ark-groth16 = { version = "0.3", default-features = false }
ark-mnt4-753 = "0.3"
ark-mnt6-753 = "0.3"
ark-relations = "0.3"
ark-r1cs-std = "0.3.1"
ark-serialize = "0.3"
ark-std = "0.3"
ark-sponge = { git = "https://github.com/arkworks-rs/sponge" }

nimiq-bls = { path = "../bls" }
nimiq-zkp-primitives = { path = "../zkp-primitives", default-features = false }
nimiq-primitives = { path = "../primitives", features = ["policy"] }
parking_lot = { git = "https://github.com/styppo/parking_lot.git" }
nimiq-zkp-circuits = { path = "../zkp-circuits" }

[dev-dependencies]
nimiq-test-log = { path = "../test-log" }

[features]
zkp-prover = ["ark-crypto-primitives/r1cs", "ark-mnt4-753/r1cs", "ark-mnt6-753/r1cs", "ark-groth16/r1cs"]
parallel = ["ark-crypto-primitives/parallel", "nimiq-zkp-circuits/parallel", "ark-ec/parallel", "ark-ff/parallel", "ark-std/parallel", "ark-groth16/parallel", "nimiq-zkp-primitives/parallel"]

[[example]]
name = "setup"
path = "examples/prover/setup.rs"
required-features = ["zkp-prover", "parallel"]

[[example]]
name = "prove"
path = "examples/prover/prove.rs"
required-features = ["zkp-prover", "parallel"]
