[package]
name = "nimiq-subscription"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Subscription primitives to be used in Nimiq's Albatross implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }

[dependencies]
bitflags = "1.0"
hex = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
serde = "1.0"

nimiq-bls = { path = "../../bls", features = ["serde-derive"] }
nimiq-hash = { path = "../../hash" }
nimiq-keys = { path = "../../keys" }
nimiq-macros = { path = "../../macros" }
nimiq-primitives = { path = "..", features = ["policy", "networks", "account", "coin"] }
nimiq-serde = { path = "../../serde" }
nimiq-transaction = { path = "../transaction" }
nimiq-utils = { path = "../../utils", features = ["merkle"] }

[dev-dependencies]
hex = "0.4"
