[package]
name = "nimiq-subscription"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Subscription primitives to be used in Nimiq's Albatross implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }

[lints]
workspace = true

[dependencies]
hex = "0.4"
log = { workspace = true }
serde = "1.0"

nimiq-bls = { workspace = true, features = ["serde-derive"] }
nimiq-hash = { workspace = true }
nimiq-keys = { workspace = true }
nimiq-macros = { workspace = true }
nimiq-primitives = { workspace = true, features = ["policy", "networks", "account", "coin"] }
nimiq-serde = { workspace = true }
nimiq-transaction = { workspace = true }
nimiq-utils = { workspace = true, features = ["merkle"] }

[dev-dependencies]
hex = "0.4"
