[package]
name = "nimiq-pedersen-generators"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
license = "MIT/Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2021"

[dependencies]
beserial = { path = "../../beserial", features = ["derive"] }

nimiq-bls = { path = "../../bls" }
nimiq-primitives = { path = "../../primitives", features = ["policy"] }
