[package]
name = "nimiq-pedersen-generators"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[[bench]]
name = "generate"
harness = false

[dependencies]
ark-crypto-primitives = { version = "0.4", features = ["crh"] }
ark-ec = "0.4"
ark-ff = "0.4"
ark-mnt6-753 = "0.4"
hex = "0.4"

nimiq-hash = { path = "../../hash" }
nimiq-primitives = { path = "../../primitives", features = ["policy"] }

[dev-dependencies]
bencher = "0.1"
