[package]
name = "nimiq-pedersen-generators"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
license = "MIT/Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2021"

[dependencies]
ark-crypto-primitives = { version = "0.4", features = ["crh"] }
ark-ec = "0.4"
ark-ff = "0.4"
ark-mnt6-753 = "0.4"
ark-serialize = "0.4"
hex = "0.4"

beserial = { path = "../../beserial", features = ["derive"] }
nimiq-hash = { path = "../../hash" }
nimiq-primitives = { path = "../../primitives", features = ["policy"] }
