[package]
name = "nimiq-blockchain"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Persistent block storage for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
parking_lot = "0.9"
log = "0.4"
hex = "0.3"
failure = "0.1"
beserial = "0.1"
beserial_derive = "0.1"
nimiq-keys = "0.1"
nimiq-primitives = "0.1"
nimiq-account = "0.1"
nimiq-block = "0.1"
nimiq-transaction = "0.1"
nimiq-hash = "0.1"
nimiq-accounts = "0.1"
nimiq-database = { version = "0.1", features = ["full-nimiq"] }
nimiq-tree-primitives = "0.1"
fixed-unsigned = "0.1"
nimiq-utils = { version = "0.1", features = ["observer", "unique-ptr", "iterators"] }
nimiq-network-primitives = { version = "0.1", features = ["networks", "time"] }
nimiq-blockchain-base = "0.1"

[dev-dependencies]
atomic = "0.4"

[features]
default = ["transaction-store"]
metrics = ["nimiq-blockchain-base/metrics"]
transaction-store = []
