[package]
name = "nimiq-blockchain"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Persistent block storage for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
beserial = { path = "../beserial" }
beserial_derive = { path = "../beserial/beserial_derive"}
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives" }
nimiq-account = { path = "../primitives/account" }
nimiq-block = { path = "../primitives/block" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-hash = { path = "../hash" }
nimiq-accounts = { path = "../accounts" }
nimiq-database = { path = "../database", features = ["full-nimiq"] }
nimiq-tree-primitives = { path = "../accounts/tree-primitives" }
fixed-unsigned = { path = "../fixed-unsigned" }
nimiq-utils = { path = "../utils", features = ["observer", "unique-ptr", "iterators"] }
nimiq-network-primitives = { path = "../network-primitives", features = ["networks", "time"] }
parking_lot = "0.7"
log = "0.4"
hex = "0.3"
failure = "0.1"

[dev-dependencies]
atomic = "0.4"

[features]
default = ["transaction-store"]
metrics = []
transaction-store = []
