[package]
name = "nimiq-time"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "tokio::time for Rust and WASM"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
gloo-timers = { version = "0.2", features = ["futures"] }
send_wrapper = { version = "0.6", features = ["futures"] }
tokio = { version = "1.36", features = ["time"] }
tokio-stream = { version = "0.1", features = ["time"] }
