[network]
peer_key_file = "/home/nimiq/peer_key.dat"
listen_addresses = [
    "/ip4/0.0.0.0/tcp/8443/ws",
]
advertised_addresses = [
    "/dns4/validator1/tcp/8443/ws", # Docker-internal
    "/dns4/validator1.nimiq.local/tcp/8501/ws" # Docker-external
]
allow_loopback_addresses = true
dht_quorum = 3

seed_nodes = [
        { address = "/dns4/seed1/tcp/8443/ws" }
]

autonat_allow_non_global_ips = true
desired_peer_count = 3

[consensus]
network = "dev-albatross"
sync_mode = "history"
min_peers = 3

[database]
path = "/home/nimiq"

[log]
level = "info"
timestamps = true

# [log.tags]
# libp2p_swarm = "debug"
# lock_api = "trace"

[validator]
automatic_reactivate = true
validator_address = "NQ31 RL44 3HXF 26SY YNY5 GQJM LAUT ARHB 8LV9"
signing_key_file = "/home/nimiq/signing_key.dat"
signing_key = "d655bfc597525bd884e87e4da1b5f9aabcd268a69c3ad667f4958e3fc34bb709"
voting_key_file = "/home/nimiq/voting_key.dat"
voting_key = "bb23e2feff1423a17d7e87023c05d9d3975030db8a35f163da61ab6241a1e9a7f02c004ed7296a220e48a65ab7a8f5febbf372f2fef07cfc3da872de3f4df2edc4521a326631b47d71ceb8a2438e63ec040eae5db0fbabeb9d9e9dfa011300"
fee_key_file = "/home/nimiq/fee_key.dat"
fee_key = "bf482fd2946f7c16c5a85a6b4fa728a31bbf6b53dd3c259c315986d7f3cc0737"
