[package]
name = "nimiq-consensus"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Consensus implementation of Nimiq in Rust"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
parking_lot = "0.9"
rand = "0.6"
log = "0.4"
weak-table = "0.2"
failure = "0.1"
futures = "0.1"
tokio = "0.1"
beserial = { version = "0.1" }
nimiq-hash = { version = "0.1" }
nimiq-macros = { version = "0.1" }
nimiq-block-base = { version = "0.1" }
nimiq-blockchain = { version = "0.1", features = ["transaction-store"] }
nimiq-blockchain-albatross = { version = "0.1", features = ["transaction-store"] }
nimiq-blockchain-base = { version = "0.1" }
nimiq-transaction = { version = "0.1" }
nimiq-mempool = { version = "0.1" }
nimiq-collections = { version = "0.1" }
nimiq-primitives = { version = "0.1", features = ["policy"] }
nimiq-messages = { version = "0.1" }
nimiq-network-primitives = { version = "0.1", features = ["networks", "time"] }
nimiq-network = { version = "0.1" }
nimiq-database = { version = "0.1", features = ["full-nimiq"] }
nimiq-utils = { version = "0.1", features = ["observer", "timers", "mutable-once", "throttled-queue", "rate-limit", "merkle", "math"] }
nimiq-block-albatross = { version = "0.1" }
