[package]
name = "nimiq-test-log"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { package = "tracing", version = "0.1", features = ["log"] }
parking_lot = "0.12"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

nimiq-log = { path = "../log" }
nimiq-primitives = { path = "../primitives", features = ["policy"] }
nimiq-test-log-proc-macro = { path = "proc-macro" }
