[package]
name = "nimiq-rpc-server"
version = "0.0.1"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "JSON RPC server for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
nimiq-blockchain = { path = "../blockchain" }
nimiq-accounts = { path = "../accounts" }
nimiq-consensus = { path = "../consensus" }
nimiq-network = { path = "../network" }
nimiq-database = { path = "../database" }
nimiq-hash = { path = "../hash" }
nimiq-network-primitives = { path = "../network-primitives" }
nimiq-primitives = { path = "../primitives", features = ["all"] }
beserial = { path = "../beserial" }

hyper = "0.12.19"
json = "0.11.13"

url = "1.7"
tokio = "0.1"
tokio-tls = "0.2"
native-tls = "0.2"
futures = "0.1"
byteorder = "1.2"
tungstenite = "0.6"
tokio-tungstenite = { git = "https://github.com/jeffesquivels/tokio-tungstenite", branch = "implement_peer_addr" }
regex = "1"
pretty_env_logger = "0.2.3"

bigdecimal = "0.0.14"
parking_lot = "0.6"
lazy_static = "1.0"
log = "0.4.3"
lmdb-zero = "0.4.4"
hex = "0.3.2"
