[package]
name = "nimiq-rpc-server"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "JSON RPC server for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
hyper = "0.12"
json = "0.11"
futures = "0.1"
log = "0.4"
hex = "0.3"
failure = "0.1"
parking_lot = "0.9"
base64 = "0.10"
beserial = "0.1"
clear_on_drop = { version = "0.2" }
nimiq-database = "0.1"
nimiq-consensus = "0.1"
nimiq-blockchain = "0.1"
nimiq-blockchain-albatross = "0.1"
nimiq-blockchain-base = "0.1"
nimiq-bls = "0.1"
nimiq-mempool = "0.1"
nimiq-network = "0.1"
nimiq-hash = "0.1"
nimiq-network-primitives = "0.1"
nimiq-block = "0.1"
nimiq-block-albatross = "0.1"
nimiq-block-base = "0.1"
nimiq-transaction = "0.1"
nimiq-keys = "0.1"
nimiq-block-production = "0.1"
nimiq-utils = { version = "0.1", features = ["merkle", "time", "otp"] }
nimiq-primitives = "0.1"
nimiq-wallet = "0.1"
