[package]
name = "nimiq-transaction"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Transaction primitive to be used in Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }

[dependencies]
bitflags = "1.0"
log = "0.4"
failure = "0.1"
beserial = { path = "../../beserial", version = "0.1.0" }
beserial_derive = { path = "../../beserial/beserial_derive", version = "0.1.0" }
nimiq-hash = { path = "../../hash", version = "0.1.0" }
nimiq-keys = { path = "../../keys", version = "0.1.0" }
nimiq-utils = { path = "../../utils", version = "0.1.0", features = ["merkle"] }
nimiq-primitives = { path = "..", version = "0.1.0", features = ["policy", "networks", "account", "coin"] }
nimiq-bls = { path = "../../bls", version = "0.1.0", features = ["beserial"] }

[dev-dependencies]
hex = "0.3"
