[package]
name = "nimiq-tools"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Tools for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[[bin]]
name = "nimiq-bls"
path = "src/bls/main.rs"

[[bin]]
name = "nimiq-address"
path = "src/address/main.rs"

[[bin]]
name = "nimiq-signtx"
path = "src/signtx/main.rs"

[dependencies]
nimiq-bls = "0.1"
nimiq-hash = "0.1"
nimiq-keys = "0.1"
nimiq-build-tools = "0.1"
nimiq-transaction = "0.1"
nimiq-primitives = "0.1"
beserial = "0.1"
log = "0.4"
simple_logger = "1.0"
hex = "0.4"
rand = "0.7"
clap = "2.33"
failure = "0.1"
