[package]
name = "nimiq-tools"
version = "0.1.0"
authors = ["Janosch Gräf <janosch@nimiq.com>"]
edition = "2018"

[[bin]]
name = "nimiq-bls"
path = "src/bls/main.rs"

[[bin]]
name = "nimiq-address"
path = "src/address/main.rs"

[dependencies]
nimiq-bls = { path = "../bls" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-build-tools = { path = "../build-tools" }
log = "0.4"
simple_logger = "1.0"
hex = "0.3"
rand = "0.6"
