[package]
name = "nimiq-tools"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Tools for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[[bin]]
name = "nimiq-bls"
path = "src/bls/main.rs"

[[bin]]
name = "nimiq-address"
path = "src/address/main.rs"

[[bin]]
name = "nimiq-signtx"
path = "src/signtx/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.3", features = ["cargo"] }
hex = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
rand = "0.8"
thiserror = "1.0"

nimiq-bls = { path = "../bls" }
nimiq-hash = { path = "../hash" }
nimiq-keys = { path = "../keys" }
nimiq-primitives = { path = "../primitives" }
nimiq-transaction = { path = "../primitives/transaction" }
nimiq-serde = { path = "../serde" }
nimiq-utils = { path = "../utils" }
