[package]
name = "nimiq-trie"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Merkle radix trie primitive for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
hex = "0.4"
log = { package = "tracing", version = "0.1", features = ["log"] }
serde = "1.0"
thiserror = "1.0"

nimiq-database = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-primitives = { workspace = true, features = ["key-nibbles", "serde-derive", "trie"] }
nimiq-serde = { workspace = true }

[dev-dependencies]
nimiq-test-log = { workspace = true }
