[package]
name = "nimiq-web-client"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2021"
description = "Nimiq's Rust to wasm web client"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]
exclude = ["db", "peer_key.dat"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = { package = "futures-util", version = "0.3" }
gloo-timers = "0.2"
log = { package = "tracing", version = "0.1", features = ["log"] }
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

beserial = { path = "../beserial", features = ["derive"] }
nimiq-blockchain-interface = { path = "../blockchain-interface" }
nimiq-blockchain-proxy = { path = "../blockchain-proxy", default-features = false }
nimiq-consensus = { path = "../consensus", default-features = false }
nimiq-hash = { path = "../hash" }
nimiq-network-interface = { path = "../network-interface" }

[dependencies.nimiq]
package = "nimiq-lib"
path = "../lib"
version = "0.1"
default-features = false
features = [
    "panic",
    "wasm-websocket",
    "web-logging",
]

[dev-dependencies]
parking_lot = "0.12"
wasm-bindgen-test = "0.3"

beserial = { path = "../beserial", features = ["derive"] }
nimiq-bls = {path = "../bls"}
nimiq-blockchain-proxy = {path = "../blockchain-proxy", default-features = false}
nimiq-consensus = {path = "../consensus", default-features = false}
nimiq-genesis = {path = "../genesis", default-features = false}
nimiq-light-blockchain = {path = "../light-blockchain"}
nimiq-network-interface = {path = "../network-interface"}
nimiq-network-mock = {path = "../network-mock"}
nimiq-primitives = {path = "../primitives", features = ["networks"]}
nimiq-zkp-component = {path = "../zkp-component", default-features = false}
