[package]
name = "nimiq-compile-zkp-setup"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
license = "MIT/Apache-2.0"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
edition = "2021"

[dependencies]
ark-ec = "0.3"
ark-groth16 = "0.3"
ark-mnt6-753 = "0.3"
ark-serialize = "0.3"
rand = { version = "0.8", features = ["small_rng"] }
rand_chacha = "0.3.1"

nimiq-nano-primitives = { path = "../../nano-primitives", features = ["zkp-prover"] }

