name: Build + Test Code Coverage

on:
  schedule:
    - cron: '0 12 * * 0'  # run on Sundays at 12
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        swap-storage: true
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: llvm-tools-preview
    - uses: Swatinem/rust-cache@v2
    - name: Install Protoc
      run: sudo apt-get install protobuf-compiler
    - name: Install cargo-nextest
      run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov
    - name: Remove possible stale artifacts
      run: cargo llvm-cov clean --workspace
    - name: Run test with coverage instrumentation
      run: cargo llvm-cov nextest --all-features --profile ci
      # Fixme: --doctest is not supported in stable. See:
      # https://github.com/taiki-e/cargo-llvm-cov/tree/7448e48b438797efb446a98ebd8ff22d3fae5ebe#known-limitations
      # run: cargo llvm-cov --all-features --doctests
    - name: Generate coverage report
      run: cargo llvm-cov report --lcov --output-path coverage.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.lcov
        fail_ci_if_error: false
        flags: unittests
        name: Nimiq code coverage
        verbose: true